// ===============================================================
// =================== FIREBASE INITIALIZATION ===================
// ===============================================================
import { initializeApp } from "https://www.gstatic.com/firebasejs/9.15.0/firebase-app.js";
import { getAuth, GoogleAuthProvider, signInWithPopup, onAuthStateChanged, createUserWithEmailAndPassword, signInWithEmailAndPassword, sendPasswordResetEmail } from "https://www.gstatic.com/firebasejs/9.15.0/firebase-auth.js";
import { getFirestore, collection, getDocs, doc, getDoc, setDoc, query, where, updateDoc, runTransaction, arrayUnion, arrayRemove, writeBatch, limit, serverTimestamp, addDoc, orderBy } from "https://www.gstatic.com/firebasejs/9.15.0/firebase-firestore.js";

const firebaseConfig = { apiKey: "AIzaSyBflzOWVf3HgDpdUhha3qvyeUJf7i6dOuk", authDomain: "wine-91d0e.firebaseapp.com", projectId: "wine-91d0e", storageBucket: "wine-91d0e.firebasestorage.app", messagingSenderId: "1021620433427", appId: "1:1021620433427:web:5439252fb350c4455a85e6", measurementId: "G-TRWHY3KXK1" };
const app = initializeApp(firebaseConfig);
const db = getFirestore(app);
const auth = getAuth(app);

// ===============================================================
// =================== UI & HELPER FUNCTIONS =====================
// ===============================================================
const CART_STORAGE_KEY = 'vinoelite_cart';
const WISHLIST_STORAGE_KEY = 'vinoelite_wishlist';
let wishlistProductIds = new Set();

function showToast(message, type = 'info') { const container = document.getElementById('toast-container'); const toast = document.createElement('div'); toast.className = `toast ${type}`; toast.textContent = message; container.appendChild(toast); setTimeout(() => toast.classList.add('show'), 10); setTimeout(() => { toast.classList.remove('show'); toast.addEventListener('transitionend', () => toast.remove()); }, 3000); }
function getProductSlugFromUrl() { const path = window.location.pathname; const parts = path.split('/').filter(part => part); return (parts.length >= 2 && parts[0] === 'catalog') ? parts[parts.length - 1] : null; }
function generateStars(rating) { let starsHTML = ''; const fullStars = Math.floor(rating); const halfStar = rating % 1 >= 0.5; const emptyStars = 5 - fullStars - (halfStar ? 1 : 0); for (let i = 0; i < fullStars; i++) starsHTML += '<i class="fas fa-star"></i>'; if (halfStar) starsHTML += '<i class="fas fa-star-half-alt"></i>'; for (let i = 0; i < emptyStars; i++) starsHTML += '<i class="far fa-star"></i>'; return starsHTML; }

// ===============================================================
// =================== AUTHENTICATION & UI =======================
// ===============================================================
const loginModal = document.getElementById('login-modal'); const closeModalBtn = document.querySelector('.close-modal-btn'); const desktopAuthBtn = document.getElementById('auth-button'); const mobileAuthBtn = document.getElementById('mobile-auth-button'); const authForm = document.getElementById('auth-form'); const emailInput = document.getElementById('auth-email'); const passwordInput = document.getElementById('auth-password'); const errorContainer = document.getElementById('auth-error'); const forgotPasswordLink = document.getElementById('forgot-password-link');
function openLoginModal(e) { e.preventDefault(); loginModal.style.display = 'block'; } function closeLoginModal() { loginModal.style.display = 'none'; authForm.reset(); errorContainer.textContent = ''; }
document.getElementById('google-signin-btn').addEventListener('click', async () => { try { await signInWithPopup(auth, new GoogleAuthProvider()); closeLoginModal(); } catch (error) { errorContainer.textContent = error.message; } });
authForm.addEventListener('submit', async (e) => { e.preventDefault(); const email = emailInput.value; const password = passwordInput.value; errorContainer.textContent = ''; try { await signInWithEmailAndPassword(auth, email, password); closeLoginModal(); } catch (error) { if (error.code === 'auth/user-not-found') { try { await createUserWithEmailAndPassword(auth, email, password); closeLoginModal(); } catch (createError) { errorContainer.textContent = createError.message; } } else { errorContainer.textContent = error.message; } } });
forgotPasswordLink.addEventListener('click', async (e) => { e.preventDefault(); const email = emailInput.value; if (!email) { alert('Please enter your email to reset password.'); return; } try { await sendPasswordResetEmail(auth, email); alert('Password reset email sent!'); } catch (error) { alert(`Error: ${error.message}`); } });
function updateUIForAuthState(user) { if (user) { const userName = user.displayName || user.email.split('@')[0]; desktopAuthBtn.href = "/profile.html"; desktopAuthBtn.innerHTML = `<i class="fas fa-user-check"></i> <span class="auth-text">${userName}</span>`; desktopAuthBtn.title = "My Account"; desktopAuthBtn.removeEventListener('click', openLoginModal); mobileAuthBtn.href = "/profile.html"; mobileAuthBtn.querySelector('span').textContent = userName; mobileAuthBtn.removeEventListener('click', openLoginModal); } else { desktopAuthBtn.href = "#"; desktopAuthBtn.innerHTML = `<i class="far fa-user"></i> <span class="auth-text">Sign In</span>`; desktopAuthBtn.title = "Sign In"; desktopAuthBtn.addEventListener('click', openLoginModal); mobileAuthBtn.href = "#"; mobileAuthBtn.querySelector('span').textContent = 'Sign In / Register'; mobileAuthBtn.addEventListener('click', openLoginModal); } }

// ===============================================================
// =================== CART & WISHLIST LOGIC =====================
// ===============================================================
async function updateHeaderCounters() { const user = auth.currentUser; let cartItemCount = 0; let wishlistItemCount = 0; if (user) { const cartSnapshot = await getDocs(collection(db, `users/${user.uid}/cart`)); cartSnapshot.forEach(doc => { cartItemCount += doc.data().quantity; }); const userDoc = await getDoc(doc(db, "users", user.uid)); if (userDoc.exists() && userDoc.data().wishlist) { wishlistItemCount = userDoc.data().wishlist.length; wishlistProductIds = new Set(userDoc.data().wishlist); } } else { const localCart = JSON.parse(localStorage.getItem(CART_STORAGE_KEY)) || []; localCart.forEach(item => { cartItemCount += item.quantity; }); const localWishlist = JSON.parse(localStorage.getItem(WISHLIST_STORAGE_KEY)) || []; wishlistItemCount = localWishlist.length; wishlistProductIds = new Set(localWishlist); } document.querySelectorAll('.cart-count, .cart-count-badge').forEach(el => { el.textContent = cartItemCount; el.style.display = cartItemCount > 0 ? 'flex' : 'none'; }); document.querySelectorAll('.wishlist-count, .wishlist-count-badge').forEach(el => { el.textContent = wishlistItemCount; el.style.display = wishlistItemCount > 0 ? 'flex' : 'none'; }); document.querySelectorAll('.wishlist-toggle-btn').forEach(btn => { const icon = btn.querySelector('i'); if (wishlistProductIds.has(btn.dataset.productId)) { btn.classList.add('active'); icon.classList.remove('far'); icon.classList.add('fas'); } else { btn.classList.remove('active'); icon.classList.remove('fas'); icon.classList.add('far'); } }); }
async function updateProductCartStatus(productId) { const user = auth.currentUser; let quantityInCart = 0; if (user) { const cartItemRef = doc(db, `users/${user.uid}/cart`, productId); const docSnap = await getDoc(cartItemRef); if (docSnap.exists()) { quantityInCart = docSnap.data().quantity; } } else { const cart = JSON.parse(localStorage.getItem(CART_STORAGE_KEY)) || []; const existingItem = cart.find(item => item.productId === productId); if (existingItem) { quantityInCart = existingItem.quantity; } } document.querySelector('.quantity-input').value = 1; const badge = document.querySelector('#add-to-cart-btn .cart-quantity-badge'); if (badge) { if (quantityInCart > 0) { badge.textContent = quantityInCart; badge.classList.add('visible'); } else { badge.classList.remove('visible'); } } }
async function addToCart(productId, quantity, buttonElement) { const user = auth.currentUser; if (user) { const cartItemRef = doc(db, `users/${user.uid}/cart`, productId); await runTransaction(db, async (transaction) => { const cartItemDoc = await transaction.get(cartItemRef); const newQuantity = cartItemDoc.exists() ? cartItemDoc.data().quantity + quantity : quantity; transaction.set(cartItemRef, { quantity: newQuantity, addedAt: new Date() }, { merge: true }); }); } else { let cart = JSON.parse(localStorage.getItem(CART_STORAGE_KEY)) || []; const existingItem = cart.find(item => item.productId === productId); if (existingItem) { existingItem.quantity += quantity; } else { cart.push({ productId, quantity }); } localStorage.setItem(CART_STORAGE_KEY, JSON.stringify(cart)); } showToast('Added to cart!', 'success'); await updateHeaderCounters(); await updateProductCartStatus(productId); if (buttonElement) { const originalHTML = buttonElement.querySelector('span').innerHTML; buttonElement.querySelector('span').innerHTML = `Added!`; buttonElement.classList.add('added'); buttonElement.disabled = true; setTimeout(() => { buttonElement.querySelector('span').innerHTML = originalHTML; buttonElement.classList.remove('added'); buttonElement.disabled = false; }, 2000); } }
async function toggleWishlist(productId) { const user = auth.currentUser; if (user) { const userDocRef = doc(db, "users", user.uid); if (wishlistProductIds.has(productId)) { await updateDoc(userDocRef, { wishlist: arrayRemove(productId) }); showToast('Removed from wishlist.', 'danger'); } else { await updateDoc(userDocRef, { wishlist: arrayUnion(productId) }); showToast('Added to wishlist!', 'success'); } } else { let localWishlist = JSON.parse(localStorage.getItem(WISHLIST_STORAGE_KEY)) || []; const itemIndex = localWishlist.indexOf(productId); if (itemIndex > -1) { localWishlist.splice(itemIndex, 1); showToast('Removed from wishlist.', 'danger'); } else { localWishlist.push(productId); showToast('Added to wishlist! Sign in to save it.', 'info'); } localStorage.setItem(WISHLIST_STORAGE_KEY, JSON.stringify(localWishlist)); } await updateHeaderCounters(); }
async function syncDataOnAuth(user) { const localCart = JSON.parse(localStorage.getItem(CART_STORAGE_KEY)) || []; const localWishlist = JSON.parse(localStorage.getItem(WISHLIST_STORAGE_KEY)) || []; if (localCart.length === 0 && localWishlist.length === 0) return; if (localCart.length > 0) { const cartCollectionRef = collection(db, `users/${user.uid}/cart`); const batch = writeBatch(db); for (const item of localCart) { const docRef = doc(cartCollectionRef, item.productId); const docSnap = await getDoc(docRef); const newQty = docSnap.exists() ? docSnap.data().quantity + item.quantity : item.quantity; batch.set(docRef, { quantity: newQty, addedAt: new Date() }, { merge: true }); } await batch.commit(); localStorage.removeItem(CART_STORAGE_KEY); } if (localWishlist.length > 0) { const userDocRef = doc(db, "users", user.uid); await setDoc(userDocRef, { wishlist: arrayUnion(...localWishlist) }, { merge: true }); localStorage.removeItem(WISHLIST_STORAGE_KEY); } showToast('Your cart & wishlist have been synced!', 'info'); }
onAuthStateChanged(auth, async (user) => { updateUIForAuthState(user); if (user) { await syncDataOnAuth(user); } await updateHeaderCounters(); const productSlug = getProductSlugFromUrl(); if(productSlug) { const product = await fetchProductBySlug(productSlug); if(product) await updateProductCartStatus(product.id); } });

// ===============================================================
// =================== REVIEW SYSTEM LOGIC =======================
// ===============================================================
async function fetchReviewsForProduct(productId) { const reviewsQuery = query(collection(db, `products/${productId}/reviews`), orderBy('createdAt', 'desc')); const snapshot = await getDocs(reviewsQuery); const reviews = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() })); if (reviews.length === 0) return []; const userIds = [...new Set(reviews.map(review => review.userId).filter(Boolean))]; const userProfiles = {}; if (userIds.length > 0) { const userDocsPromises = userIds.map(uid => getDoc(doc(db, "users", uid))); const userDocsSnapshots = await Promise.all(userDocsPromises); userDocsSnapshots.forEach(userDoc => { if (userDoc.exists()) { const userData = userDoc.data(); userProfiles[userDoc.id] = userData.displayName || userData.email?.split('@')[0] || 'Anonymous'; } }); } return reviews.map(review => ({ ...review, userName: userProfiles[review.userId] || review.userName || 'Anonymous' })); }
function renderReviews(reviews) { const container = document.getElementById('reviews-list'); container.innerHTML = ''; if (reviews.length === 0) { container.innerHTML = '<p>No reviews yet for this product. Be the first to leave one!</p>'; return; } reviews.forEach(review => { const reviewDate = review.createdAt?.toDate().toLocaleDateString() || 'N/A'; container.innerHTML += `<div class="review-card"><div class="review-header"><div class="review-author">${review.userName}</div><div class="stars">${generateStars(review.rating)}</div></div><h4 class="review-title">${review.title}</h4><p class="review-text">${review.text}</p><div class="review-date">${reviewDate}</div></div>`; }); }
async function renderReviewForm(user, product) { const container = document.getElementById('review-form-container'); if (user) { const q = query(collection(db, `products/${product.id}/reviews`), where("userId", "==", user.uid), limit(1)); const existingReviewSnap = await getDocs(q); if (!existingReviewSnap.empty) { container.innerHTML = '<h4>Your Review</h4><p>You have already submitted a review for this product.</p>'; } else { container.innerHTML = `<h4>Leave a Review</h4><form id="review-form"><div class="form-group"><label>Your Rating</label><div class="star-rating"><input type="radio" id="star5" name="rating" value="5" required><label for="star5" title="5 stars">&#9733;</label><input type="radio" id="star4" name="rating" value="4"><label for="star4" title="4 stars">&#9733;</label><input type="radio" id="star3" name="rating" value="3"><label for="star3" title="3 stars">&#9733;</label><input type="radio" id="star2" name="rating" value="2"><label for="star2" title="2 stars">&#9733;</label><input type="radio" id="star1" name="rating" value="1"><label for="star1" title="1 star">&#9733;</label></div></div><div class="form-group"><label for="review-title">Review Title</label><input type="text" id="review-title" required></div><div class="form-group"><label for="review-text">Your Review</label><textarea id="review-text" required></textarea></div><button type="submit" class="btn-submit-review">Submit Review</button></form>`; document.getElementById('review-form').addEventListener('submit', (e) => handleReviewSubmit(e, user, product)); } } else { container.innerHTML = `<div class="login-prompt"><p>You must be <a href="#" id="login-link-in-review">signed in</a> to leave a review.</p></div>`; document.getElementById('login-link-in-review').addEventListener('click', openLoginModal); } }
async function handleReviewSubmit(e, user, product) { e.preventDefault(); const form = e.target; const rating = form.rating.value; if (!rating) { alert('Please select a star rating.'); return; } const reviewData = { userId: user.uid, userName: user.displayName || user.email.split('@')[0], rating: Number(rating), title: form['review-title'].value, text: form['review-text'].value, createdAt: serverTimestamp(), productId: product.id, productName: product.name }; try { await addDoc(collection(db, `products/${product.id}/reviews`), reviewData); const productRef = doc(db, "products", product.id); await runTransaction(db, async (transaction) => { const productDoc = await transaction.get(productRef); if (!productDoc.exists()) throw "Product does not exist!"; const oldReviewCount = productDoc.data().reviewCount || 0; const oldRatingValue = productDoc.data().ratingValue || 0; const newReviewCount = oldReviewCount + 1; const newRatingValue = ((oldRatingValue * oldReviewCount) + Number(rating)) / newReviewCount; transaction.update(productRef, { reviewCount: newReviewCount, ratingValue: parseFloat(newRatingValue.toFixed(1)) }); }); showToast('Thank you for your review!', 'success'); const reviews = await fetchReviewsForProduct(product.id); renderReviews(reviews); await renderReviewForm(user, product); } catch (error) { console.error("Error submitting review: ", error); showToast('Error submitting review. Please try again.', 'danger'); } }

// ===============================================================
// =================== PAGE RENDERING & DATA FETCHING ============
// ===============================================================
async function fetchProductBySlug(slug) { const q = query(collection(db, "products"), where("slug", "==", slug), limit(1)); const querySnapshot = await getDocs(q); return querySnapshot.empty ? null : { id: querySnapshot.docs[0].id, ...querySnapshot.docs[0].data() }; }
async function fetchRelatedProducts(currentProduct) { if (!currentProduct || !currentProduct.category) return []; const q = query(collection(db, "products"), where("category", "==", currentProduct.category), where("isArchived", "==", false), limit(5)); const querySnapshot = await getDocs(q); const related = []; querySnapshot.forEach((doc) => { if (doc.id !== currentProduct.id) related.push({ id: doc.id, ...doc.data() }); }); return related.slice(0, 4); }
function renderProduct(product) {
    // ИЗМЕНЕНИЕ: Эти строки закомментированы. "Турбо-скрипт" в HTML-файле
    // теперь отвечает за быструю установку этих SEO-тегов.
    // document.title = product.metaTitle || `${product.name} - VinoElite`;
    // document.querySelector('meta[name="description"]').content = product.metaDescription || product.description;
    
    const breadcrumbContainer = document.getElementById('breadcrumb');
    const params = new URLSearchParams();
    let breadcrumbHTML = `<a href="/index.html">Home</a> / <a href="/catalog.html">Catalog</a>`;
    if (product.category) { params.set('category', product.category); breadcrumbHTML += ` / <a href="/catalog.html?${params.toString()}">${product.category}</a>`; }
    if (product.country) { params.set('country', product.country); breadcrumbHTML += ` / <a href="/catalog.html?${params.toString()}">${product.country}</a>`; }
    if (product.region) { params.set('region', product.region); breadcrumbHTML += ` / <a href="/catalog.html?${params.toString()}">${product.region}</a>`; }
    if (product.appellation) { params.set('appellation', product.appellation); breadcrumbHTML += ` / <a href="/catalog.html?${params.toString()}">${product.appellation}</a>`; }
    breadcrumbHTML += ` / <span>${product.name}</span>`;
    breadcrumbContainer.innerHTML = breadcrumbHTML;
    const mainGalleryContainer = document.getElementById('product-gallery-main');
    const thumbnailsContainer = document.getElementById('product-thumbnails');
    const imageUrls = (product.imageUrls && product.imageUrls.length > 0) ? product.imageUrls : [product.imageUrl];
    mainGalleryContainer.innerHTML = imageUrls.map((url, i) => `<div class="slideshow-item"><img src="${url}" alt="${product.name} view ${i + 1}"></div>`).join('') + `<div class="image-badge" style="display: ${product.badge ? 'block' : 'none'}">${product.badge || ''}</div>` + `<button class="wishlist-toggle-btn" data-product-id="${product.id}"><i class="far fa-heart"></i></button>`;
    thumbnailsContainer.innerHTML = imageUrls.map(url => `<div class="thumbnail-item"><img src="${url}" alt="Thumbnail"></div>`).join('');
    const subtitleEl = document.getElementById('product-subtitle');
    let fullSubtitle = [product.category, product.sweetness].filter(Boolean).join(' ');
    const originInfo = [product.region, product.country].filter(Boolean).join(', ');
    if (originInfo) fullSubtitle += (fullSubtitle ? ' from ' : '') + originInfo;
    subtitleEl.textContent = fullSubtitle;
    document.getElementById('product-title').textContent = product.name;
    document.getElementById('product-description').textContent = product.description;
    if (product.ratingValue && product.reviewCount) { document.getElementById('product-rating').innerHTML = `<div class="stars">${generateStars(product.ratingValue)}</div><span class="rating-value">${product.ratingValue}</span><span class="rating-count">(${product.reviewCount} reviews)</span>`; }
    const detailsContainer = document.getElementById('product-details-list');
    detailsContainer.innerHTML = '';
    const detailsOrder = [ { key: 'country', label: 'Country', icon: 'fa-globe-americas' }, { key: 'region', label: 'Region', icon: 'fa-map-marker-alt' }, { key: 'appellation', label: 'Appellation', icon: 'fa-award' }, { key: 'brand', label: 'Producer', icon: 'fa-industry' }, { key: 'year', label: 'Year', icon: 'fa-calendar-alt' }, { key: 'grapeVarieties', label: 'Grapes', icon: 'fa-wine-glass' }, { key: 'sweetness', label: 'Sweetness', icon: 'fa-tint' }, { key: 'alcohol', label: 'Alcohol', icon: 'fa-percentage', suffix: '%' }, { key: 'volume', label: 'Volume', icon: 'fa-wine-bottle' } ];
    detailsOrder.forEach(detail => { if (product[detail.key]) { detailsContainer.innerHTML += `<div class="detail-item"><i class="fas ${detail.icon}"></i><span>${detail.label}: ${product[detail.key]}${detail.suffix || ''}</span></div>`; } });
    if (product.serving) { product.serving.split('\n').forEach(line => { if (line.trim() === '') return; const [key, ...value] = line.split(':'); let icon = 'fa-info-circle'; if (key.toLowerCase().includes('temp')) icon = 'fa-thermometer-half'; if (key.toLowerCase().includes('decan')) icon = 'fa-hourglass-half'; detailsContainer.innerHTML += `<div class="detail-item"><i class="fas ${icon}"></i><span>${key}: ${value.join(':')}</span></div>`; }); }
    document.getElementById('product-pricing').innerHTML = `<div class="current-price">$${product.price.toFixed(2)}</div>` + (product.oldPrice ? `<span class="old-price">$${product.oldPrice.toFixed(2)}</span>` : '');
    const stockEl = document.getElementById('product-stock-status');
    const cartBtn = document.getElementById('add-to-cart-btn');
    stockEl.textContent = product.stockStatus || 'In Stock';
    stockEl.className = 'stock-status';
    if (product.stockStatus === 'Out of Stock') { stockEl.classList.add('out-of-stock'); cartBtn.disabled = true; cartBtn.classList.add('out-of-stock'); cartBtn.querySelector('span').innerHTML = 'Out of Stock'; } else { stockEl.classList.add(product.stockStatus === 'Low Stock' ? 'low-stock' : 'in-stock'); cartBtn.disabled = false; }
    const tastingNotesTab = document.getElementById('tasting-notes-tab');
    if (product.tastingNotes) { const notesHTML = product.tastingNotes.split('\n').map(line => { const [key, ...value] = line.split(':'); return `<li><strong>${key}:</strong> ${value.join(':').trim()}</li>`; }).join(''); tastingNotesTab.innerHTML = `<h3>Tasting Notes</h3><ul class="tasting-notes-list">${notesHTML}</ul>`; } else { tastingNotesTab.innerHTML = '<h3>Tasting Notes</h3><p>No tasting notes available.</p>'; }
    const foodPairingTab = document.getElementById('food-pairing-tab');
    if (product.foodPairing) { foodPairingTab.innerHTML = `<h3>Food Pairing</h3><p class="food-pairing-content">${product.foodPairing.replace(/\n/g, '<br>')}</p>`; } else { foodPairingTab.innerHTML = '<h3>Food Pairing</h3><p>No recommendations available.</p>'; }
}
function renderRelatedProducts(products) { const grid = document.getElementById('related-products-grid'); grid.innerHTML = ''; if (!products || products.length === 0) { grid.innerHTML = '<p>No similar products found.</p>'; return; } products.forEach(prod => { const categorySlug = prod.category.toLowerCase().replace(/\s+/g, '-'); const productUrl = `/catalog/${categorySlug}/${prod.slug}`; let subtitle = [prod.category, prod.sweetness].filter(Boolean).join(' ') + (prod.region ? ` from ${[prod.region, prod.country].filter(Boolean).join(', ')}` : ''); const imageUrls = (prod.imageUrls && prod.imageUrls.length > 0) ? prod.imageUrls : [prod.imageUrl]; const card = document.createElement('div'); card.className = 'product-card animate-on-scroll'; card.dataset.url = productUrl; card.innerHTML = `<div class="slideshow-container">${imageUrls.map((url, i) => `<div class="slideshow-item"><img src="${url}" alt="${prod.name} view ${i + 1}"></div>`).join('')}${prod.badge ? `<div class="product-badge">${prod.badge}</div>` : ''}<button class="wishlist-toggle-btn" data-product-id="${prod.id}"><i class="far fa-heart"></i></button></div><div class="product-info-card"><div><div class="product-subtitle-card">${subtitle}</div><h3 class="product-name-card">${prod.name}</h3><p class="product-description-card">${prod.metaDescription || prod.description || ''}</p></div><div><div class="product-price-card"><div class="price-card">$${prod.price.toFixed(2)}</div>${prod.oldPrice ? `<div class="old-price-card">$${prod.oldPrice.toFixed(2)}</div>` : ''}</div><button class="add-to-cart-btn" data-product-id="${prod.id}"><i class="fas fa-shopping-cart"></i> Add to Cart</button></div></div>`; grid.appendChild(card); }); document.querySelectorAll('#related-products-grid .slideshow-container').forEach(setupSlideshow); }

// ===============================================================
// =================== SLIDESHOW LOGIC ===========================
// ===============================================================
function setupProductSlideshow(mainContainer, thumbnailsContainer) { const slides = Array.from(mainContainer.querySelectorAll('.slideshow-item')); const thumbnails = Array.from(thumbnailsContainer.querySelectorAll('.thumbnail-item')); if (slides.length <= 1) { if (slides.length === 1) { slides[0].classList.add('active'); if (thumbnails.length === 1) thumbnails[0].classList.add('active'); } return; } if (mainContainer.querySelector('.slideshow-overlay')) return; const overlay = document.createElement('div'); overlay.className = 'slideshow-overlay'; mainContainer.appendChild(overlay); let currentIndex = 0, intervalId = null; function resetInterval() { clearInterval(intervalId); intervalId = setInterval(() => showSlide(currentIndex + 1, false), 5000); } function showSlide(index, isManualAction = false) { if (index === currentIndex && slides[index]?.classList.contains('active')) return; if (slides[currentIndex]) slides[currentIndex].classList.remove('active'); if (thumbnails[currentIndex]) thumbnails[currentIndex].classList.remove('active'); currentIndex = (index + slides.length) % slides.length; if (slides[currentIndex]) slides[currentIndex].classList.add('active'); if (thumbnails[currentIndex]) thumbnails[currentIndex].classList.add('active'); if (isManualAction) thumbnails[currentIndex].scrollIntoView({ behavior: 'smooth', block: 'nearest', inline: 'center' }); } thumbnails.forEach((thumb, index) => { thumb.addEventListener('click', () => { if (index === currentIndex) return; showSlide(index, true); resetInterval(); }); }); let touchStartX = 0; overlay.addEventListener('mousedown', e => { touchStartX = e.clientX; overlay.style.cursor = 'grabbing'; clearInterval(intervalId); }); overlay.addEventListener('mouseup', e => { overlay.style.cursor = 'grab'; const touchEndX = e.clientX; if (touchEndX < touchStartX - 50) showSlide(currentIndex + 1, true); else if (touchEndX > touchStartX + 50) showSlide(currentIndex - 1, true); resetInterval(); }); overlay.addEventListener('touchstart', e => { touchStartX = e.touches[0].clientX; clearInterval(intervalId); }, { passive: true }); overlay.addEventListener('touchend', e => { let touchEndX = e.changedTouches[0].clientX; if (touchEndX < touchStartX - 50) showSlide(currentIndex + 1, true); else if (touchEndX > touchStartX + 50) showSlide(currentIndex - 1, true); resetInterval(); }); showSlide(0, false); resetInterval(); }
function setupSlideshow(container) { if (!container) return; const slides = Array.from(container.querySelectorAll('.slideshow-item')); if (slides.length <= 1) { if (slides.length === 1) slides[0].classList.add('active'); return; } if (container.querySelector('.slideshow-overlay')) return; const overlay = document.createElement('div'); overlay.className = 'slideshow-overlay'; container.appendChild(overlay); let currentIndex = 0; let intervalId = setInterval(() => showSlide(currentIndex + 1), 4000); function showSlide(index) { slides[currentIndex]?.classList.remove('active'); currentIndex = (index + slides.length) % slides.length; setTimeout(() => slides[currentIndex]?.classList.add('active'), 50); } function manualSlide(direction) { clearInterval(intervalId); showSlide(currentIndex + direction); intervalId = setInterval(() => showSlide(currentIndex + 1), 5000); } let touchStartX = 0; overlay.addEventListener('mousedown', e => { touchStartX = e.clientX; overlay.style.cursor = 'grabbing'; clearInterval(intervalId); }); overlay.addEventListener('mouseup', e => { overlay.style.cursor = 'grab'; if (e.clientX < touchStartX - 50) manualSlide(1); else if (e.clientX > touchStartX + 50) manualSlide(-1); else intervalId = setInterval(() => showSlide(currentIndex + 1), 5000); }); overlay.addEventListener('touchstart', e => { touchStartX = e.touches[0].clientX; clearInterval(intervalId); }, { passive: true }); overlay.addEventListener('touchend', e => { let touchEndX = e.changedTouches[0].clientX; if (touchEndX < touchStartX - 50) manualSlide(1); else if (touchEndX > touchStartX + 50) manualSlide(-1); else intervalId = setInterval(() => showSlide(currentIndex + 1), 5000); }); showSlide(0); }

// ===============================================================
// =================== EVENT LISTENERS & INITIALIZATION ==========
// ===============================================================
document.addEventListener('DOMContentLoaded', async () => {
    const loader = document.getElementById('loader');
    const mainContent = document.getElementById('main-site-content');
    const mobileMenuBtn = document.querySelector('.mobile-menu-btn');
    const navLinks = document.getElementById('main-nav');
    
    // --- HEADER & MODAL LOGIC ---
    mobileMenuBtn.addEventListener('click', () => { const isActive = navLinks.classList.toggle('active'); mobileMenuBtn.classList.toggle('active', isActive); mobileMenuBtn.innerHTML = isActive ? '<i class="fas fa-times"></i>' : '<i class="fas fa-bars"></i>'; });
    closeModalBtn.addEventListener('click', closeLoginModal);
    window.addEventListener('click', (e) => { if (e.target == loginModal) closeLoginModal(); });
    
    // --- SCROLL ANIMATION LOGIC ---
    const animationObserver = new IntersectionObserver((entries) => { entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add('is-visible'); } else { entry.target.classList.remove('is-visible'); } }); }, { threshold: 0.1 });
    document.querySelectorAll('.animate-on-scroll').forEach(el => animationObserver.observe(el));
    const observeDynamicContent = (container) => { if (!container) return; const mutationObserver = new MutationObserver(mutations => { mutations.forEach(mutation => { mutation.addedNodes.forEach(node => { if (node.nodeType === 1) { node.querySelectorAll('.animate-on-scroll').forEach(el => animationObserver.observe(el)); if (node.classList.contains('animate-on-scroll')) animationObserver.observe(node); } }); }); }); mutationObserver.observe(container, { childList: true, subtree: true }); };
    observeDynamicContent(document.getElementById('related-products-grid'));

    // --- MAIN PAGE LOGIC ---
    const productSlug = getProductSlugFromUrl();
    if (!productSlug) { document.querySelector('.product-section .container').innerHTML = '<h2>Product not found.</h2>'; loader.classList.add('hidden'); mainContent.classList.add('loaded'); return; }

    try {
        await updateHeaderCounters();
        const product = await fetchProductBySlug(productSlug);
        if (!product) { document.querySelector('.product-section .container').innerHTML = '<h2>Product not found.</h2>'; return; }
        
        const [relatedProducts, reviews] = await Promise.all([ fetchRelatedProducts(product), fetchReviewsForProduct(product.id) ]);

        renderProduct(product);
        setupProductSlideshow(document.getElementById('product-gallery-main'), document.getElementById('product-thumbnails'));
        renderRelatedProducts(relatedProducts);
        renderReviews(reviews);
        await updateProductCartStatus(product.id);
        
        onAuthStateChanged(auth, (user) => { renderReviewForm(user, product); });

        // --- EVENT LISTENERS ---
        const quantityInput = document.querySelector('.quantity-input');
        document.querySelector('.quantity-btn.minus').addEventListener('click', () => { let val = parseInt(quantityInput.value); if (val > 1) quantityInput.value = val - 1; });
        document.querySelector('.quantity-btn.plus').addEventListener('click', () => { quantityInput.value = parseInt(quantityInput.value) + 1; });
        document.getElementById('add-to-cart-btn').addEventListener('click', (e) => { addToCart(product.id, parseInt(quantityInput.value), e.currentTarget); });
        document.querySelector('.product-gallery-main').addEventListener('click', (e) => { const wishlistBtn = e.target.closest('.wishlist-toggle-btn'); if (wishlistBtn) toggleWishlist(wishlistBtn.dataset.productId); });
        document.querySelector('.tabs-header').addEventListener('click', e => { const tabBtn = e.target.closest('.tab-btn'); if (tabBtn) { document.querySelectorAll('.tab-btn, .tab-content').forEach(el => el.classList.remove('active')); tabBtn.classList.add('active'); document.getElementById(`${tabBtn.dataset.tab}-tab`).classList.add('active'); } });
        document.getElementById('related-products-grid').addEventListener('click', function(e) { const cartButton = e.target.closest('.add-to-cart-btn'); const wishlistButton = e.target.closest('.wishlist-toggle-btn'); if (cartButton) { e.preventDefault(); e.stopPropagation(); addToCart(cartButton.dataset.productId, 1, cartButton); } else if (wishlistButton) { e.preventDefault(); e.stopPropagation(); toggleWishlist(wishlistButton.dataset.productId); } else { const card = e.target.closest('.product-card'); if (card && card.dataset.url) window.location.href = card.dataset.url; } });
        const mobileSearchForm = document.querySelector('.mobile-search .search-box'); if (mobileSearchForm) { const mobileSearchInput = mobileSearchForm.querySelector('input'); mobileSearchForm.addEventListener('submit', (e) => { e.preventDefault(); const query = mobileSearchInput.value.trim(); if (query) { window.location.href = `/catalog.html?search=${encodeURIComponent(query)}`; } }); }

    } catch (error) {
        console.error("Error loading product page:", error);
        document.querySelector('.product-section .container').innerHTML = '<h2>Error loading product details. Please try again.</h2>';
    } finally {
        loader.classList.add('hidden');
        mainContent.classList.add('loaded');
    }
});